config/routes.rb
Rails.application.routes.draw do
root "comments#index"
resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :all_comments, only: [:index, :create]
  respond_to :html, :js

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(comment_params)
  end

  private

    def all_comments
      @comments = Comment.all
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<h2><%= comment.content %></h2>

app/views/comments/_form.html.erb
<%= simple_form_for @comment, remote: true do |f| %>
  <%= f.input  :content %>
  <%= f.button :submit %>
<% end %>

app/views/comments/create.js.erb
$('#comments').html("<%=escape_javascript(render @comments) %>");
$('#comment-form').slideUp(350);

app/views/comments/index.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h2>Comments</h2>
  </div>

  <div class="col-md-2 col-md-offset-4">
    <%= link_to new_comment_path, remote: true do %>
      <button class="btn btn-default">New</button>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-2" id="comment-form" ></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="comments"><%= render @comments %></div>
</div>

app/views/comments/new.js.erb
$('#comment-form').html("<%=escape_javascript(render 'form') %>");
$('#comment-form').slideDown(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommentSubmit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>